version: '3'
services:
  dns.service:
    image: "dnsimage:latest"
    build: .
    volumes:
      - type: bind
        source: ./bind
        target: /etc/bind
    ports:
      - "192.168.25.40:53:53/udp"    