version: '3'
services:
  dns.service:
    restart: always
    container_name: dns_container
    image: "dnsimage:latest"
    build: .
    volumes:
      - ./bind:/etc/bind 
    ports:
      - "192.168.25.40:53:53/udp"